import tseslint from "typescript-eslint";

// Root-level linting covers repository tooling only (scripts/, root configs).
// Workspace packages are linted per-package through Turbo with the boundary
// rules generated by scripts/eslint-package-config.mjs.
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/coverage/**",
      "**/.turbo/**",
      "packages/**",
      "apps/**",
      "prisma/**",
    ],
  },
  ...tseslint.configs.recommended,
);
